// Map Material Design icon names to emoji equivalents
const iconNameToEmoji: Record<string, string> = {
  // Common icons from Chrome extension
  'text_snippet': '📝',
  'code': '💻',
  'lightbulb': '💡',
  'rocket_launch': '🚀',
  'star': '⭐',
  'work': '💼',
  'target': '🎯',
  'auto_fix_high': '✨',
  'build': '🛠️',
  'analytics': '📊',
  'palette': '🎨',
  'search': '🔍',
  'phone_android': '📱',
  'psychology': '🧠',
  'school': '🎓',
  'business_center': '💼',
  'email': '📧',
  'chat': '💬',
  'settings': '⚙️',
  'help': '❓',
  'info': 'ℹ️',
  'warning': '⚠️',
  'error': '❌',
  'check_circle': '✅',
  'favorite': '❤️',
  'thumb_up': '👍',
  'download': '⬇️',
  'upload': '⬆️',
  'share': '🔗',
  'copy': '📋',
  'edit': '✏️',
  'delete': '🗑️',
  'visibility': '👁️',
  'lock': '🔒',
  'key': '🔑',
  'shield': '🛡️',
  'speed': '⚡',
  'timer': '⏱️',
  'calendar_today': '📅',
  'event': '📅',
  'folder': '📁',
  'file_copy': '📄',
  'image': '🖼️',
  'video_library': '🎬',
  'music_note': '🎵',
  'mic': '🎤',
  'headphones': '🎧',
  'camera': '📷',
  'photo_camera': '📸',
  'location_on': '📍',
  'map': '🗺️',
  'directions': '🧭',
  'home': '🏠',
  'apartment': '🏢',
  'store': '🏪',
  'restaurant': '🍽️',
  'local_cafe': '☕',
  'local_bar': '🍺',
  'fitness_center': '💪',
  'spa': '🧘',
  'beach_access': '🏖️',
  'flight': '✈️',
  'train': '🚂',
  'directions_car': '🚗',
  'directions_bike': '🚲',
  'trending_up': '📈',
  'trending_down': '📉',
  'account_balance': '🏦',
  'credit_card': '💳',
  'shopping_cart': '🛒',
  'local_shipping': '🚚',
  'inventory': '📦',
  'receipt': '🧾',
  'calculate': '🧮',
  'biotech': '🧬',
  'eco': '🌱',
  'wb_sunny': '☀️',
  'nights_stay': '🌙',
  'cloud': '☁️',
  'umbrella': '☂️',
  'ac_unit': '❄️',
  'whatshot': '🔥',
  'pets': '🐾',
  'child_care': '👶',
  'elderly': '👴',
  'face': '😊',
  'mood': '😄',
  'sentiment_very_satisfied': '😆',
  'celebration': '🎉',
  'cake': '🎂',
  'sports_esports': '🎮',
  'sports_soccer': '⚽',
  'sports_basketball': '🏀',
  'sports_tennis': '🎾',
  'swimming_pool': '🏊',
  'hiking': '🥾',
  'park': '🌳',
  'nature': '🌿',
  'local_florist': '🌸',
  'bug_report': '🐛',
  'extension': '🧩',
  'integration_instructions': '🔗',
  'api': '🔌',
  'data_usage': '📊',
  'storage': '💾',
  'cloud_upload': '☁️',
  'backup': '💿',
  'restore': '🔄',
  'refresh': '🔄',
  'sync': '🔄',
  'update': '🔄',
  'new_releases': '🆕',
  'notifications': '🔔',
  'volume_up': '🔊',
  'volume_off': '🔇',
  'wifi': '📶',
  'signal_cellular_4_bar': '📶',
  'battery_full': '🔋',
  'power': '⚡',
  'developer_mode': '👨‍💻',
  'code_blocks': '💻',
  'terminal': '💻',
  'functions': '🔧',
  'api_key': '🔑',
  'token': '🎫',
  'security': '🔒',
  'vpn_key': '🔑',
  'verified': '✅',
  'check': '✅',
  'close': '❌',
  'clear': '❌',
  'cancel': '❌',
  'block': '🚫',
  'do_not_disturb': '🚫',
  'report': '📋',
  'assignment': '📄',
  'description': '📝',
  'note': '📝',
  'sticky_note_2': '🗒️',
  'bookmark': '🔖',
  'label': '🏷️',
  'sell': '🏷️',
  'local_offer': '🏷️',
  'loyalty': '🎖️',
  'workspace_premium': '💎',
  'diamond': '💎',
  'savings': '💰',
  'paid': '💰',
  'payment': '💳',
  'point_of_sale': '💳',
  'receipt_long': '🧾',
  'price_check': '🏷️',
  'price_change': '🏷️',
  'trending_flat': '➡️',
  'arrow_forward': '➡️',
  'arrow_back': '⬅️',
  'arrow_upward': '⬆️',
  'arrow_downward': '⬇️'
};

/**
 * Convert Material Design icon name to emoji
 * If no mapping exists, return a default emoji
 */
export const convertIconToEmoji = (iconName: string): string => {
  // If it's already an emoji (single character with unicode > 127), return as-is
  if (iconName.length <= 4 && /[\u{1F600}-\u{1F64F}]|[\u{1F300}-\u{1F5FF}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/u.test(iconName)) {
    return iconName;
  }
  
  // Convert Material Design icon name to emoji
  return iconNameToEmoji[iconName] || '📝'; // Default to document emoji
};

/**
 * Check if a string is likely a Material Design icon name
 */
export const isMaterialIcon = (iconName: string): boolean => {
  return iconName.includes('_') || iconNameToEmoji.hasOwnProperty(iconName);
};